#Extend the official Rasa SDK image
FROM rasa/rasa-sdk:1.10.2

#Use subdirectory as working directory
WORKDIR /app

#Copy any additional custom requirements, if necessary (uncomment next line)
#COPY actions/requirements.txt ./

#Change back to root user to install dependencies
USER root

#Copy actions folder to working directory
COPY ./actions /app/actions